project_id = "bifqtxaigahdhejurzyb"

[functions.telegram-notification]
verify_jwt = false

[functions.process-message-queue]
verify_jwt = false

[functions.ultramsg-webhook]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.send-whapi]
verify_jwt = false

[functions.whatsapp-webjs-proxy]
verify_jwt = false

[functions.send-whatsapp-webjs]
verify_jwt = false

[functions.whatsapp-webjs-webhook]
verify_jwt = false