// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jclbkyyujtrpfqgrmdhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjbGJreXl1anRycGZxZ3JtZGhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MTUyNjEsImV4cCI6MjA2NjQ5MTI2MX0.4HnhQrgyKBtmNQYO5ON4XnCzL_zeqB6IKRALd975GpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);