// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zctueazyrxqmxgjnnogz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjdHVlYXp5cnhxbXhnam5ub2d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MzgzMTAsImV4cCI6MjA2NjMxNDMxMH0.sWNUNTna4I8c4qdSu8RJ2r20J_d64kTHFAesbrCHej8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);